### ISSUE TITLE
W3C Validation is NOK

### ISSUE THREAD

**Issue by tetsumaki** [isso-comments/isso#328]
Hello,

The html code from isso is unfortunately not validated by the [w3c validator](https://validator.w3.org/) at 2 locations :

### 1 :

```html
<section class="auth-section">
```
**Warning :** Section lacks heading. Consider using `h2`-`h6` elements to [add identifying headings to all sections](https://www.w3.org/wiki/HTML/Usage/Headings/Missing).

### 2 :

```html
<div role="meta" class="isso-comment-header">
````
**Error :** Bad value `meta` for attribute `role` on element [div](http://www.w3.org/html/wg/drafts/html/master/single-page.html#the-div-element).

**Comment by ix5** [comment]
Feel free to fix those, but as this is purely cosmetic, I'm going to close this issue.

**Comment by mhellmeier** [comment]
I would suggest reopening this issue since it isn't a purely cosmetic thing. When optimizing web pages, things like `role="meta"` will fail, for example, in the Lighthouse checks of the accessibility category because it isn't a correct [ARIA role](https://dequeuniversity.com/rules/axe/4.8/aria-roles).
